server:
  port: ${PORT:8080}

spring:
  graphql:
    path: /graphql
    graphiql:
      enabled: false   

backend:
  base-url: ${BACKEND_BASE_URL}

logging:
  level:
    org.springframework.graphql: INFO
    org.springframework.web.reactive.function.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
